import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MessageSquare,Brain,CheckSquare,Blocks,Settings,Plus,ArrowUp,Square,Sun,Moon,ChevronRight,PanelLeft,Folder,FileText,Terminal,Monitor,ShieldCheck,Link2,RefreshCw,Trash2,Sparkles,ArrowRight,Globe,Lock,ChevronDown,Check,AlertCircle} from 'lucide-react';
import type {Snapshot,Result,Space} from './shared';
import './style.css';
function App(){
 const [data,setData]=useState<Snapshot|null>(null),[page,setPage]=useState('chat'),[draft,setDraft]=useState(''),[pending,setPending]=useState(false),[review,setReview]=useState(false),[localError,setLocalError]=useState('');
 const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{window.agent.snapshot().then(r=>{if(r.ok)setData(r.value);else setLocalError(r.error);});return window.agent.onChange(setData);},[]);
 const chat=data?.state.chats.find(c=>c.id===data.state.active);
 useEffect(()=>{setDraft(chat?.draft||'');setReview(false);},[chat?.id]);
 useEffect(()=>{if(data)document.documentElement.dataset.theme=data.state.theme;},[data?.state.theme]);
 useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[chat?.messages.at(-1)?.text]);
 useEffect(()=>{if(data?.runtime.account==='chatgpt')setLocalError('');},[data?.runtime.account]);
 if(!data)return <div className="loading"><Sparkles/><h2>Personal Agent</h2><p>{localError||'Loading your local workspace…'}</p></div>;
 const {state,runtime}=data,zh=state.language==='zh';
 const t=(en:string,cn:string)=>zh?cn:en;
 const busy=runtime.busy||pending;
 const names:Record<Space,string>={personal:t('Personal','个人'),lab:t('Lab','实验'),work:t('Work · local only','工作 · 仅本地')};
 const call=async<T,>(fn:()=>Promise<Result<T>>)=>{setPending(true);setLocalError('');try{const r=await fn();if(!r.ok)setLocalError(r.error);return r;}catch(e){setLocalError(String(e));}finally{setPending(false);}};
 const pref=(p:any)=>call(()=>window.agent.preferences(p));
 const send=async()=>{if(!chat||!draft.trim()||busy)return;setReview(false);const r=await call(()=>window.agent.send(chat.id,draft));if(r?.ok&&r.value)setDraft('');};
 const status=runtime.account==='chatgpt'?t('ChatGPT connected','ChatGPT 已连接'):runtime.connected?t('Sign-in required','等待登录'):t('Not connected','未连接');
 const nav=[['chat',MessageSquare,t('Chat','聊天')],['memory',Brain,t('Memory','记忆')],['tasks',CheckSquare,t('Tasks','任务')],['skills',Blocks,'Skills']] as const;
 const chatPane=<div className="conversation">
  <div className="conversation-top"><div><span className="eyebrow">{t('YOUR PERSONAL SPACE','你的个人空间')}</span><h2>{chat?.title||t('A little clarity, every day.','让每一天，更有条理。')}</h2></div><button className="icon-button" disabled={busy} title={t('Delete conversation','删除对话')} onClick={()=>chat&&call(()=>window.agent.deleteChat(chat.id))}><Trash2 size={16}/></button></div>
  <div className="messages" aria-live="polite">
   {!chat?.messages.length?<div className="welcome"><div className="welcome-icon"><Sparkles size={30}/></div><h1>{state.space==='work'?t('A private place for your notes.','留给工作记录的本地空间。'):t('What’s on your mind?','今天想聊些什么？')}</h1><p>{state.space==='work'?t('Notes stay on this computer. No cloud AI requests.','记录只留在这台电脑，不调用云端 AI。'):t('Make room for an idea, a question, or your next project.','从一个想法、一个问题，或下一个项目开始。')}</p><div className="suggestions">{[t('Plan my learning week','规划这一周的学习'),t('Think through an idea','一起梳理一个想法'),t('Explain a piece of code','解释一段代码')].map(s=><button key={s} onClick={()=>{setDraft(s);if(chat)void window.agent.draft(chat.id,s);}}>{s}<ArrowRight size={14}/></button>)}</div></div>:
   chat.messages.map(m=><div className={'message '+m.role} key={m.id}>{m.role==='assistant'&&<div className="avatar"><Sparkles size={17}/></div>}<div className="message-content"><span className="message-name">{m.role==='user'?t('You','你'):'Personal Agent'}</span><div className="message-body">{m.text||(m.status==='streaming'?t('Thinking…','正在思考…'):t('No response text','暂无回复内容'))}</div>{m.status&&m.status!=='completed'&&<small className="message-state">{m.status==='streaming'?t('Responding','正在回复'):m.status==='interrupted'?t('Interrupted','已中断'):t('Failed · see details below','失败 · 请查看下方信息')}</small>}</div></div>)}<div ref={end}/>
  </div>
  <div className="composer-area"><div className="composer"><textarea aria-label={t('Your message','输入消息')} maxLength={16000} disabled={runtime.busy} value={draft} placeholder={state.space==='work'?t('Write a local note…','写一条本地记录…'):t('Ask anything…','随时问我…')} onChange={e=>{setDraft(e.target.value);if(chat)void window.agent.draft(chat.id,e.target.value).then(r=>{if(!r.ok)setLocalError(r.error);});}} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();if(draft.trim()&&!busy)state.space==='work'?void send():setReview(true);}}}/><div className="composer-bottom"><span><Lock size={13}/>{state.space==='work'?t('On this device only','仅保存在本机'):t('Review before sending','发送前预览')}<span className="key-hint">Ctrl ↵</span></span>{runtime.busy?<button className="send" title={t('Stop','停止')} onClick={()=>void call(()=>window.agent.stop())}><Square size={16}/></button>:<button className="send" title={t('Review & send','预览并发送')} disabled={busy||!draft.trim()} onClick={()=>state.space==='work'?void send():setReview(true)}><ArrowUp size={19}/></button>}</div></div><div className="composer-note"><span className="status-dot"/>{state.space==='work'?t('Cloud access blocked','已阻止云端访问'):t('ChatGPT plan · no API fallback','ChatGPT 套餐 · 不回退到付费 API')}<span>{draft.length.toLocaleString()} / 16,000</span></div></div>
 </div>;
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-icon"><Sparkles size={20}/></div><span>Personal Agent<small>PREVIEW 0.4</small></span></div>
   <button className="new-chat" disabled={busy} onClick={()=>{setPage('chat');void call(()=>window.agent.newChat());}}><Plus size={17}/>{t('New conversation','新对话')}</button>
   <nav>{nav.map(([key,Icon,label])=><button className={page===key?'selected':''} key={key} onClick={()=>setPage(key)}><Icon size={18}/><span>{label}</span>{key!=='chat'&&<small>{t('Soon','待开发')}</small>}</button>)}</nav>
   <div className="recents-label">{t('RECENT CONVERSATIONS','最近对话')}<span>{state.chats.filter(c=>c.space===state.space).length}</span></div>
   <div className="recents">{state.chats.filter(c=>c.space===state.space).map(c=><button key={c.id} disabled={busy} className={c.id===chat?.id?'active':''} onClick={()=>{setPage('chat');void call(()=>window.agent.select(c.id));}}><MessageSquare size={14}/><span>{c.title||t('New conversation','新对话')}</span></button>)}</div>
   <div className="sidebar-bottom"><div className="plan-card"><span className="plan-symbol"><Link2 size={17}/></span><div><strong>{t('Your ChatGPT plan','你的 ChatGPT 套餐')}</strong><small>{status}</small></div><span className={'dot '+(runtime.account==='chatgpt'?'online':'')}/></div><button className={'settings-nav '+(page==='settings'?'selected':'')} onClick={()=>setPage('settings')}><Settings size={18}/>{t('Settings','设置')}<ChevronRight size={15}/></button><div className="theme-row"><span>{t('Appearance','外观')}</span><button className="icon-button" disabled={busy} title={t('Switch theme','切换主题')} onClick={()=>pref({theme:state.theme==='light'?'dark':'light'})}>{state.theme==='light'?<Moon size={17}/>:<Sun size={17}/>}</button></div></div>
  </aside>
  <main><header><div className="header-left"><PanelLeft size={17}/><span>{page==='chat'?t('My workspace','我的空间'):page==='settings'?t('Preferences','偏好设置'):t('Coming next','即将加入')}</span></div><div className="mode-switch"><button className={state.mode==='chat'?'on':''} disabled={busy} onClick={()=>{setPage('chat');void pref({mode:'chat'});}}>{t('Chat','聊天模式')}</button><button className={state.mode==='workbench'?'on':''} disabled={busy} onClick={()=>{setPage('chat');void pref({mode:'workbench'});}}>{t('Workbench','工作台')}</button></div><select aria-label={t('Space','空间')} value={state.space} disabled={busy} onChange={e=>pref({space:e.target.value})}>{spacesList.map(s=><option key={s} value={s}>{names[s]}</option>)}</select></header>
   <div className="preview-strip"><span className="preview-tag">PREVIEW</span>{t('First checkpoint: local chat & plan connection. More tools are on the roadmap.','首个阶段：本地对话与套餐连接。更多工具将在后续阶段加入。')}<span className="model-tag">GPT-6 Astra</span></div>
   {(localError||runtime.error)&&<div className="error" role="alert"><AlertCircle size={17}/><span>{localError||runtime.error}</span><button onClick={()=>{setLocalError('');}} title={t('Dismiss local error','清除本地提示')}>×</button></div>}
   {page==='settings'?<div className="settings-page"><span className="eyebrow">PERSONAL AGENT</span><h1>{t('Make it yours.','设置你的助手。')}</h1><p className="muted">{t('Preferences and sign-in stay on this computer.','偏好设置与登录信息保存在这台电脑。')}</p>
    <section><h3><Link2 size={19}/>{t('ChatGPT connection','ChatGPT 连接')}</h3><div className="connection-summary"><span className={'dot '+(runtime.account==='chatgpt'?'online':'')}/><strong>{status}</strong><span>{runtime.plan}</span></div><p>{t('Sign in with your ChatGPT account in your browser. This preview uses a separate Codex login and does not copy credentials from the desktop app.','在浏览器中使用 ChatGPT 账号登录。预览版使用独立的 Codex 登录，不复制桌面应用的凭据。')}</p><div className="button-row"><button className="primary" disabled={busy} onClick={()=>call(()=>window.agent.login())}>{t('Sign in with ChatGPT','使用 ChatGPT 登录')}<ArrowRight size={15}/></button><button disabled={busy} onClick={()=>call(()=>window.agent.connect())}>{t('Connect / reconnect','连接 / 重新连接')}</button><button disabled={busy||!runtime.connected} onClick={()=>call(()=>window.agent.refresh())}><RefreshCw size={14}/>{t('Refresh','刷新')}</button><button disabled={busy||runtime.account==='none'} onClick={()=>call(()=>window.agent.logout())}>{t('Sign out','退出登录')}</button></div><div className="info-grid"><div><small>{t('Runtime','运行程序')}</small><span>{runtime.version||t('Not checked','尚未检查')}</span></div><div><small>{t('Plan usage','套餐使用情况')}</small><span>{runtime.quota==='unknown'?t('Unknown','未知'):runtime.quota+'% '+t('used (highest window)','已用（最高窗口）')}</span></div></div><p className="small-note">{t('Usage is shared with Codex. No API fallback or automatic credit purchase. Check your account’s paid-credit settings. Live model access has not been verified for this release.','与 Codex 共享额度。不回退 API，也不自动购买额度；请检查账号付费积分设置。本发布尚未验证真实模型调用。')}</p></section>
    <section><h3><Sun size={19}/>{t('Appearance & language','外观与语言')}</h3><div className="setting-row"><span>{t('Theme','主题')}</span><div className="pill-group">{(['light','dark'] as const).map(v=><button key={v} disabled={busy} className={state.theme===v?'chosen':''} onClick={()=>pref({theme:v})}>{v==='light'?<Sun size={15}/>:<Moon size={15}/>} {v==='light'?t('Light','浅色'):t('Dark','深色')}</button>)}</div></div><div className="setting-row"><span>{t('Interface language','界面语言')}</span><select value={state.language} disabled={busy} onChange={e=>pref({language:e.target.value})}><option value="zh">简体中文</option><option value="en">English</option></select></div></section>
    <section><h3><ShieldCheck size={19}/>{t('Local data & runtime','本地数据与运行程序')}</h3><p>{t('This preview has its own data folder. Your v0.3 chats and memory are not modified or migrated. Do not place this folder in OneDrive.','预览版使用独立数据目录，不修改或迁移 v0.3 的对话和记忆。请勿将此目录放入 OneDrive。')}</p><code>{data.dataPath}</code><div className="setting-row"><span>Codex executable</span><button disabled={busy} onClick={()=>call(()=>window.agent.chooseCodex())}>{t('Choose codex.exe','选择 codex.exe')}</button></div><code>{state.codexPath||t('Auto-detect local installation','自动检测本机安装')}</code></section>
   </div>:page!=='chat'?<div className="planned-page"><div className="welcome-icon">{page==='skills'?<Blocks size={30}/>:page==='memory'?<Brain size={30}/>:<CheckSquare size={30}/>}</div><span className="eyebrow">{t('ON THE ROADMAP','已加入开发计划')}</span><h1>{page==='skills'?t('Skills, built around you.','让助手拥有你的专属技能。'):page==='memory'?t('Context that stays with you.','让重要的背景持续陪伴你。'):t('Keep the next step in sight.','让下一步始终清晰。')}</h1><p>{t('This module is not available in this preview. Your existing v0.3 features remain in the previous app.','这个模块尚未在预览版实现。原有 v0.3 功能仍可在旧版使用。')}</p><div className="roadmap-cards">{(page==='skills'?[t('Import a local skill','导入本地 Skill'),t('Install from GitHub','从 GitHub 安装'),t('Create with your assistant','与助手一起创建')]:page==='memory'?[t('Hybrid capture & confirmation','混合记忆与确认'),t('Review, edit and forget','查看、编辑和忘记'),t('Selective automatic sync','按范围自动同步')]:[t('Goals and next steps','目标与下一步'),t('Reminders on both computers','两台电脑主动提醒'),t('Operation progress','操作进度')]).map(s=><div key={s}><CheckSquare size={18}/><span>{s}</span><small>{t('Planned','待开发')}</small></div>)}</div><button onClick={()=>setPage('chat')}>{t('Back to chat','返回聊天')}<ArrowRight size={15}/></button></div>:state.mode==='chat'?chatPane:<div className="workbench"><aside className="project-pane"><div className="pane-title"><Folder size={15}/>{t('PROJECT','项目')}</div><div className="empty-project"><Folder size={28}/><strong>{t('Project tools coming next','项目工具将在后续加入')}</strong><p>{t('No project files are being read.','当前未读取任何项目文件。')}</p></div><div className="project-section"><span className="eyebrow">{t('DEVELOPMENT PLAN','开发计划')}</span>{[t('Connection & chat','连接与聊天'),t('Memory & OneDrive','记忆与 OneDrive'),t('Skills & scoped tools','Skills 与授权工具')].map((s,i)=><div key={s}><span className={'step '+(i===0?'current':'')}>{i+1}</span>{s}</div>)}</div></aside><div className="workbench-center">{chatPane}<div className="bottom-pane"><div className="pane-title"><Monitor size={15}/>{t('LAB ENVIRONMENT','实验环境')}<span>{t('Planned','待开发')}</span></div><div className="vm-summary"><Monitor size={25}/><div><strong>Ubuntu 22.04.5 LTS</strong><small>Tomcat 9.0.108 · AM 7.2.1</small></div><span className="muted">{t('Not connected','未连接')}</span></div></div></div></div>}
   <footer><span><ShieldCheck size={12}/>{state.space==='work'?t('Local-only workspace','仅本地工作空间'):t('Text chat preview · execution disabled','文字聊天预览 · 未开放执行')}</span><span>{busy?t('Working…','处理中…'):t('Ready','就绪')}<span className="dot online"/></span></footer>
  </main>
  {review&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="review-title"><div className="modal-icon"><ShieldCheck size={22}/></div><h2 id="review-title">{t('Review before sending','发送前确认')}</h2><p>{t('Your message and up to 20 recent completed messages from this conversation will be sent through Codex to the cloud. No other conversations, files or memories are attached.','你的消息和本对话最近最多 20 条已完成消息将通过 Codex 发送到云端。不附带其他对话、文件或记忆。')}</p><div className="review-text">{draft}</div><small>{t('Do not send confidential work information.','请勿发送工作机密。')}</small><div className="button-row"><button onClick={()=>setReview(false)}>{t('Back','返回')}</button><button className="primary" disabled={busy} onClick={()=>void send()}>{t('Send with my plan','使用套餐发送')}<ArrowUp size={15}/></button></div></div></div>}
 </div>;
}
const spacesList:Space[]=['personal','lab','work'];
createRoot(document.getElementById('root')!).render(<App/>);
